language: php
php:
  - '7.0'
before_install:
  - composer install --no-interaction
script:
  - vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: young-retreat-46272
