version: '2'
services:
  web:
    image: nginx:1.10.1
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/devops-symfony
      - ./nginx/do.symfony.dev.conf:/etc/nginx/conf.d/do.symfony.dev.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./:/var/www/devops-symfony
