version: '2'
services:
  web:
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/devops-symfony
      - ./nginx/do.symfony.dev.conf:/etc/nginx/conf.d/do.symfony.dev.conf
    links:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/devops-symfony
